# Fitzpatrick Categorization Based on Ethnicity

### Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
train_data1=pd.read_csv("/content/drive/MyDrive/fairface_resampling/fitz_undersampled_train.csv")

In [ ]:
train_data=train_data1.copy()

In [ ]:
test_data1=pd.read_csv("/content/drive/MyDrive/fairface_resampling/fitz_undersampled_test.csv")

In [ ]:
test_data=test_data1.copy()

## Train Data

#### White

Filter out white ethnicity

In [ ]:
filter_white=['East Asian','Latino_Hispanic','Black','Indian','Southeast Asian', 'Middle Eastern']
train_white = train_data[~train_data.race.isin(filter_white)]

In [ ]:
train_white.head()

    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ...   race service_test phototype
3            3           686             748  ...  White        False    I & II
14          14          6886            7425  ...  White        False    I & II
29          29          6899            7439  ...  White        False    I & II
40          40          6908            7451  ...  White        False    I & II
50          50          6917            7460  ...  White         True    I & II

[5 rows x 10 columns]

Rename white ethnicity to "I & II" phototype

In [ ]:
train_white["phototype"] = "I & II"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

Sort 'file' in Ascending Order

In [ ]:
train_white_sorted=train_white.sort_values("file")

Export to CSV

(The same process is repeated for each ehtnicity in the training set and the testing set.)

In [ ]:
train_white_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/train_subcategories/train_white.csv')

#### East Asian

In [ ]:
filter_east_asian=['White','Latino_Hispanic','Black','Indian','Southeast Asian', 'Middle Eastern']
train_east_asian = train_data[~train_data.race.isin(filter_east_asian)]

In [ ]:
train_east_asian.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
0            0             0  ...          True        III
2            2            66  ...         False        III
20          20          6891  ...          True        III
21          21          6892  ...          True        III
23          23          6893  ...          True        III

[5 rows x 10 columns]

In [ ]:
train_east_asian["phototype"] = "III"

In [ ]:
train_east_asian_sorted=train_east_asian.sort_values("file")

In [ ]:
train_east_asian_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/train_subcategories/train_east_asian.csv')

#### Latino-Hispanic

In [ ]:
filter_latino_hispanic=['White','East Asian','Black','Indian','Southeast Asian', 'Middle Eastern']
train_latino_hispanic = train_data[~train_data.race.isin(filter_latino_hispanic)]

In [ ]:
train_latino_hispanic.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
6            6          6879  ...          True         IV
7            7          6880  ...         False         IV
12          12          6884  ...         False         IV
15          15          6887  ...          True         IV
18          18          6889  ...          True         IV

[5 rows x 10 columns]

In [ ]:
train_latino_hispanic["phototype"] = "IV"

In [ ]:
train_latino_hispanic_sorted=train_latino_hispanic.sort_values("file")

In [ ]:
train_latino_hispanic_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/train_subcategories/train_latino_hispanic.csv')

#### Indian,Southeast asian, Middle Eastern

In [ ]:
filter_mis=['White','East Asian','Black','Latino_Hispanic']
train_mis = train_data[~train_data.race.isin(filter_mis)]

In [ ]:
train_mis.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
1            1             7  ...         False          V
4            4          6877  ...         False          V
5            5          6878  ...         False          V
10          10          6882  ...          True          V
11          11          6883  ...         False          V

[5 rows x 10 columns]

In [ ]:
train_mis["phototype"] = "V"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
train_mis_sorted=train_mis.sort_values("file")

In [ ]:
train_mis_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/train_subcategories/train_mis.csv')

#### Black

In [ ]:
filter_black=['White','East Asian','Latino_Hispanic','Indian','Southeast Asian', 'Middle Eastern']
train_black = train_data[~train_data.race.isin(filter_black)]

In [ ]:
train_black.head()

    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ...   race service_test phototype
8            8           687             749  ...  Black        False        VI
9            9          6881            7419  ...  Black         True        VI
16          16           688             750  ...  Black        False        VI
17          17          6888            7427  ...  Black         True        VI
24          24          6894            7433  ...  Black         True        VI

[5 rows x 10 columns]

In [ ]:
train_black["phototype"] = "VI"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
train_black_sorted=train_black.sort_values("file")

In [ ]:
train_black_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/train_subcategories/train_black.csv')

## Test

#### White

In [ ]:
test_white = test_data[~test_data.race.isin(filter_white)]

In [ ]:
test_white.head()

    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ...   race service_test phototype
9            9          7047            7403  ...  White        False    I & II
12          12          7049            7405  ...  White        False    I & II
23          23          7059            7415  ...  White        False    I & II
24          24          7060            7416  ...  White         True    I & II
39          39           695             728  ...  White         True    I & II

[5 rows x 10 columns]

In [ ]:
test_white["phototype"] = "I & II"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
test_white_sorted=test_white.sort_values("file")

In [ ]:
test_white_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/test_subcategories/test_white.csv')

#### East Asian

In [ ]:
test_east_asian = test_data[~test_data.race.isin(filter_east_asian)]

In [ ]:
test_east_asian.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
0            0            73  ...          True        III
2            2          7040  ...          True        III
8            8          7046  ...         False        III
14          14          7051  ...         False        III
15          15          7052  ...          True        III

[5 rows x 10 columns]

In [ ]:
test_east_asian["phototype"] = "III"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
test_east_asian_sorted=test_east_asian.sort_values("file")

In [ ]:
test_east_asian_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/test_subcategories/test_east_asian.csv')

#### Latino_Hispanic

In [ ]:
filter_latino_hispanic=['White','East Asian','Black','Indian','Southeast Asian', 'Middle Eastern']
test_latino_hispanic = test_data[~test_data.race.isin(filter_latino_hispanic)]

In [ ]:
test_latino_hispanic.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
1            1           691  ...          True         IV
7            7          7045  ...         False         IV
13          13          7050  ...         False         IV
18          18          7055  ...         False         IV
20          20           693  ...         False         IV

[5 rows x 10 columns]

In [ ]:
test_latino_hispanic["phototype"] = "IV"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
test_latino_hispanic_sorted=test_latino_hispanic.sort_values("file")

In [ ]:
test_latino_hispanic_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/test_subcategories/test_latino_hispanic.csv')

#### Indian,Southeast asian, Middle Eastern

In [ ]:
filter_mis=['White','East Asian','Black','Latino_Hispanic']
test_mis = test_data[~test_data.race.isin(filter_mis)]

In [ ]:
test_mis.head()

    Unnamed: 0  Unnamed: 0.1  ...  service_test  phototype
3            3          7041  ...         False          V
4            4          7042  ...         False          V
5            5          7043  ...         False          V
10          10           692  ...         False          V
11          11          7048  ...          True          V

[5 rows x 10 columns]

In [ ]:
test_mis["phototype"] = "V"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
test_mis_sorted=test_mis.sort_values("file")

In [ ]:
test_mis_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/test_subcategories/test_mis.csv')

#### Black

In [ ]:
filter_black=['White','East Asian','Latino_Hispanic','Indian','Southeast Asian', 'Middle Eastern']
test_black = test_data[~test_data.race.isin(filter_black)]

In [ ]:
test_black.head()

    Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ...   race service_test phototype
6            6          7044            7400  ...  Black        False        VI
17          17          7054            7410  ...  Black         True        VI
25          25          7061            7417  ...  Black        False        VI
29          29          7065            7421  ...  Black         True        VI
33          33          7068            7425  ...  Black         True        VI

[5 rows x 10 columns]

In [ ]:
test_black["phototype"] = "VI"

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
test_black_sorted=test_black.sort_values("file")

In [ ]:
test_black_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/test_subcategories/test_black.csv')

### Final CSV

Append all phototype CSV files into a single CSV file

Train

In [ ]:
train1=train_white.append(train_east_asian)

In [ ]:
train2=train1.append(train_latino_hispanic)

In [ ]:
train3=train2.append(train_mis)

In [ ]:
train4=train3.append(train_black)

In [ ]:
train_sorted=train4.sort_values("file")

In [ ]:
train_sorted.head()

      Unnamed: 0  Unnamed: 0.1  ... service_test phototype
0              0             0  ...         True       III
7              7             9  ...        False         V
66            78            99  ...        False       III
686          748           999  ...        False    I & II
6877        7415         10003  ...        False         V

[5 rows x 8 columns]

In [ ]:
train_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/fitz_type_train_final.csv')

Test

In [ ]:
test1=test_white.append(test_east_asian)

In [ ]:
test2=test1.append(test_latino_hispanic)

In [ ]:
test3=test2.append(test_mis)

In [ ]:
test4=test3.append(test_black)

In [ ]:
test_sorted=test4.sort_values("file")

In [ ]:
test_sorted.to_csv('/content/drive/MyDrive/fairface_resampling/fitzpatrick_categorization/fitz_type_test_final.csv')